### PR TITLE
Removed tabs from indentation

### PR DESCRIPTION
**Pull request by pattyland**
I messed up here with the tabs and broke version 1.5 :(

Would be great if you could release a healthy version again, otherwise I would do a rollback: https://github.com/home-assistant/core/issues/43568

### CODE REVIEW

**Comment by k0rventen** [comment]
Hey man. Just deleted v1.5 from pypi. Merging to master should push the new 1.5.

**Comment by k0rventen** [comment]
unfortunately I can't delete and upload a new, fixed v1.5 to pypi. This means I will bump version to 1.5.1, but any dependancy on v 1.5 will be buggy..

**Comment by k0rventen** [comment]
1.5.1 is available : https://pypi.org/project/avea/1.5.1/. Dependancies can now be upgraded if the version was specified :) 

keep me posted on the upstream issue on home-assistant !

**Comment by pattyland** [comment]
Next time I will test more :(

The PR at Home Assistant is here: https://github.com/home-assistant/core/pull/43618

**Pull request merged**
